service: geotiff-server

provider:
  name: aws
  runtime: nodejs6.10
  stage: production

  region: us-west-2

  iamRoleStatements:
  -  Effect: "Allow"
     Action:
       - "s3:GetObject"
     Resource:
       - "arn:aws:s3:::landsat-pds/*"

package:
  artifact: ./dist/bundle.zip

functions:
  geotiff-server:
    handler: app.app
    memorySize: 1536
    timeout: 20
    events:
      - http:
          path: tiles/{proxy+}
          method: get
          cors: true